2020-02-04 12:04:05,376 ERROR : Exception on /user/user1 [GET] [in c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Skirda\Documents\Smart guide\Flask_web\app\routes.py", line 86, in user
    return render_template('user.html', user = user, posts = posts)
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Skirda\Documents\Smart guide\Flask_web\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Skirda\Documents\Smart guide\Flask_web\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Skirda\Documents\Smart guide\Flask_web\app\templates\user.html", line 12, in block "content"
    <p><a href="{{ url_for('edit_profile') }}">Редактировать профиль</a></p>
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\skirda\.virtualenvs\flask_web-frwpird9\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'user' instead?
2020-02-04 14:01:34,730 INFO : Microblog startup [in C:\Users\Skirda\Documents\Smart guide\Flask_web\app\__init__.py:44]
2020-02-04 14:01:57,556 INFO : Microblog startup [in C:\Users\Skirda\Documents\Smart guide\Flask_web\app\__init__.py:44]
2020-02-18 17:02:27,355 INFO : Microblog startup [in C:\Users\skird\Documents\Smart guide\Flask_web\app\__init__.py:44]
